name: Python CI on feature

on:
  push:
    branches: 
      - 'feature/**'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pytest and coverage
      run: |
        pip install pytest coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest tests/
        coverage report
